### ISSUE TITLE
Permission in TRADEMARKS.md?

### ISSUE THREAD

**Issue by davelab6** [mooniak/yaldevi-fonts#56]
Regarding https://github.com/mooniak/ayanna-font/blob/master/TRADEMARKS.md I wonder that where libre foundries have TRADEMARKS.md files, they ought to have something like these inside...

* https://wikimediafoundation.org/wiki/Trademark_policy

* https://www.mozilla.org/en-US/foundation/trademarks/policy/

**Comment by davelab6** [comment]
@pathumego thoughts? :)

**Comment by pathumego** [comment]
Yep, but trademark for this might noot get through. Lawyer said it might not get the status since `Ayanna` is too ambiguous. Application is in the processing.  But meantime, yes, a some guide on how to use is essential. Im thinking for mooniak projects Its better to put everything on a single repo and link from there for meta stuff like this...

- Contribution guidelines for font projects
- Trademark Guidelines
- Tools used

I started drafting this while ago that in mind..https://github.com/mooniak/sinhala-font-tools/blob/gh-pages/libre-type-workflow.md

**Comment by pathumego** [comment]
Renamed the family
